name: Payload Dumper Benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        impl: [main, go]
        input: [zip, bin]

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y hyperfine unzip wget cargo git

      - name: Prepare ${{ matrix.impl }}
        run: |
          if [ "${{ matrix.impl }}" = "main" ]; then
            git clone --branch main https://github.com/rhythmcache/payload-dumper-rust.git dumper-main
            cd dumper-main
            cargo build --release
            mv target/release/payload_dumper ../payload_dumper
          else
            wget -q https://github.com/ssut/payload-dumper-go/releases/download/1.3.0/payload-dumper-go_1.3.0_linux_amd64.tar.gz -O pdgo.tar.gz
            tar -xzf pdgo.tar.gz
            mv payload-dumper-go ../payload_dumper
            chmod +x ../payload_dumper
          fi

      - name: Download OTA zip
        run: |
          wget -q https://dl.google.com/dl/android/aosp/comet-ota-ad1a.240530.030-98066022.zip -O ota.zip

      - name: Extract payload.bin
        run: |
          unzip -j ota.zip 'payload.bin' -d .
          ls -lh payload.bin

      - name: Run benchmark
        run: |
          if [ "${{ matrix.input }}" = "zip" ]; then
            hyperfine \
              --export-json benchmark_${{ matrix.impl }}_${{ matrix.input }}.json \
              './payload_dumper ota.zip'
          else
            hyperfine \
              --export-json benchmark_${{ matrix.impl }}_${{ matrix.input }}.json \
              './payload_dumper payload.bin'
          fi

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ matrix.impl }}-${{ matrix.input }}
          path: benchmark_${{ matrix.impl }}_${{ matrix.input }}.json
